modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TheKingElessar/Minecraft_Magic/issues"
displayURL="https://github.com/TheKingElessar/Minecraft_Magic"
authors="TheKingElessar"

[[mods]]
	modId="minecraftmagic"
	version="${file.jarVersion}"
	displayName="Minecraft Magic"
	description='''
        Adds magic to Minecraft.
	'''

	[[dependencies.minecraftmagic]]
	    modId="forge"
	    mandatory=true
	    versionRange="[25.0.108,)"
	    ordering="NONE"
	    side="BOTH"

	[[dependencies.minecraftmagic]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.13.2]"
	    ordering="NONE"
	    side="BOTH"